Switch to GH error message workflow command

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -19,16 +19,13 @@ jobs:
       - name: Check for permission to run CI
         env:
           GH_TOKEN: ${{ secrets.BOT_TOKEN }}
-        if: ${{ env.GH_TOKEN == '' }}
+        # Temporarily != to ensure it fails
+        if: ${{ env.GH_TOKEN != '' }}
         shell: bash
+        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-error-message
         run: | 
-          if [ \"$SECRET\" == \"\" ]; then
-            echo \"Pull requests made by users not in the organization (intentionally) can't access the CI secrets. Ignore this CI failure - the team will be building the project locally anyways to test it out." >> $GITHUB_OUTPUT
-            exit 1
-          else
-            echo \"Temporarily fail this case anyways as a test" >> $GITHUB_OUTPUT
-            exit 2
-          fi
+          echo "::error title=External Contributor PR::Pull requests made by users not in the organization (intentionally) can't access the CI secrets. Ignore this CI failure - the team will be building the project locally anyways to test it out."
+          exit 1
 
       - uses: actions/checkout@v2
         with:
